name: Main

on:
  push:
    branches: [develop]

concurrency:
  group: main-build
  cancel-in-progress: true

jobs:
  unit:
    uses: ./.github/workflows/_unit.yml
  e2e:
    uses: ./.github/workflows/_e2e.yml
